# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\phone_num\新建文件夹\main_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.pushButton_filechoose = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_filechoose.setGeometry(QtCore.QRect(204, 60, 61, 23))
        self.pushButton_filechoose.setObjectName("pushButton_filechoose")
        self.lineEdit_file_path = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_file_path.setGeometry(QtCore.QRect(31, 63, 131, 19))
        self.lineEdit_file_path.setReadOnly(True)
        self.lineEdit_file_path.setObjectName("lineEdit_file_path")
        self.textBrowser_log = QtWidgets.QTextBrowser(self.centralWidget)
        self.textBrowser_log.setGeometry(QtCore.QRect(411, 51, 381, 251))
        self.textBrowser_log.setObjectName("textBrowser_log")
        self.pushButton_Recognize = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_Recognize.setGeometry(QtCore.QRect(300, 60, 75, 23))
        self.pushButton_Recognize.setObjectName("pushButton_Recognize")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralWidget)
        self.textBrowser.setGeometry(QtCore.QRect(410, 340, 381, 241))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(30, 110, 71, 16))
        self.label.setObjectName("label")
        self.textBrowser_company = QtWidgets.QTextBrowser(self.centralWidget)
        self.textBrowser_company.setGeometry(QtCore.QRect(30, 140, 271, 41))
        self.textBrowser_company.setObjectName("textBrowser_company")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(30, 220, 54, 12))
        self.label_2.setObjectName("label_2")
        self.textBrowser_phone = QtWidgets.QTextBrowser(self.centralWidget)
        self.textBrowser_phone.setGeometry(QtCore.QRect(30, 250, 256, 81))
        self.textBrowser_phone.setObjectName("textBrowser_phone")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "金卫士小助手V0.2"))
        self.pushButton_filechoose.setText(_translate("MainWindow", "..."))
        self.lineEdit_file_path.setText(_translate("MainWindow", "文件路径"))
        self.pushButton_Recognize.setText(_translate("MainWindow", "识别"))
        self.label.setText(_translate("MainWindow", "公司名"))
        self.label_2.setText(_translate("MainWindow", "电话"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
